/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-03-01 15:36:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trade_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" >\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Trade 0.1 Beta</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");

bean.TradeSystemBean tradeSys = (bean.TradeSystemBean)pageContext.getServletContext().getAttribute("tradingsystem");
bean.UserBean user = (bean.UserBean)pageContext.getSession().getAttribute("user");
bean.OrderBean order;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.print(request.getParameter("message"));
      out.write("\n");
      out.write("\n");
      out.write("<h3>Addera ett vÃ¤rdepapper</h3>\n");
      out.write("<form action=\"/TradeController\">\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"addSecurity\">\n");
      out.write("<input type=\"text\" name=\"security\" value=\"\"><br>\n");
      out.write("<input type=\"submit\" value=\"UtfÃ¶r\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<h3>LÃ¤gg en kÃ¶p/sÃ¤ljorder pÃ¥ ett vÃ¤rdepapper</h3>\n");
      out.write("<form action=\"/TradeController\">\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"addOrder\">\n");
      out.write("VÃ¤rdepapper: <select name=\"security\">\n");

for(String security : tradeSys.getAllSecurities()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(security );
      out.write('"');
      out.write('>');
      out.print(security );
      out.write("</option>\n");
}
      out.write("\n");
      out.write("</select><br>\n");
      out.write("KÃ¶p: <input type=\"radio\" name=\"buyOrSell\" value=\"B\" checked>\n");
      out.write("SÃ¤lj: <input type=\"radio\" name=\"buyOrSell\" value=\"S\"><br>\n");
      out.write("Pris: <input type=\"text\" name=\"price\" value=\"\"><br>\n");
      out.write("Antal: <input type=\"text\" name=\"amount\" value=\"\"><br>\n");
      out.write("<input type=\"submit\" value=\"UtfÃ¶r\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<h3>Visa avslutade affÃ¤rer i ett vÃ¤rdepapper</h3>\n");
      out.write("<form action=\"/TradeController\">\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"viewTrades\">\n");
      out.write("VÃ¤rdepapper: <select name=\"security\">\n");
      out.write("<option value=\"Ericsson\">Ericsson</option>\n");
      out.write("<option value=\"Ericsson\">Telia</option>\n");
      out.write("<option value=\"Ericsson\">Volvo</option>\n");
      out.write("</select><br>\n");
      out.write("<input type=\"submit\" value=\"UtfÃ¶r\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
